classdef BESS_Visualization
    % BESS_Visualization - Handles all result visualization
    
    methods (Static)
        function plotSOCDistribution(SOC_history)
            figure;
            histogram(SOC_history, 'BinWidth', 2, 'Normalization', 'probability');
            xlabel('State of Charge [%]');
            ylabel('Occurrence [% of time]');
            title(sprintf('SOC Distribution (Mean: %.1f%%)', mean(SOC_history)));
            grid on;
            xlim([0 100]);
        end
        
        function plotERateDistribution(E_rate_history)
            figure;
            histogram(E_rate_history, 'BinWidth', 0.05, ...
                'Normalization', 'probability');
            xlabel('E-rate [1/h]');
            ylabel('Occurrence [% of time]');
            title('E-rate Distribution During Operation');
            grid on;
        end
        
        function plotSimulationOverview(t_data, f_data, SOC_history)
            figure;
            subplot(2,1,1);
            plot(t_data/3600, f_data);
            xlabel('Time [hours]');
            ylabel('Frequency [Hz]');
            title('Grid Frequency');
            grid on;
            
            subplot(2,1,2);
            plot(t_data/3600, SOC_history);
            xlabel('Time [hours]');
            ylabel('State of Charge [%]');
            title('BESS SOC Over Time');
            grid on;
        end
        
        function displayResults(results)
            % Create formatted output string
            output = sprintf(['\n' ...
                '=== BESS OPERATION RESULTS ===\n\n' ...
                'Total Energy Flows:\n' ...
                '  Total Charged:     %6.2f MWh (from all sources)\n' ...
                '  Total Discharged:  %6.2f MWh (from all sources)\n\n' ...
                'Schedule Transaction Analysis:\n' ...
                '  Charged via ST:    %6.2f MWh (%5.1f%% of total charging)\n' ...
                '  Discharged via ST: %6.2f MWh (%5.1f%% of total discharging)\n\n' ...
                'Calculation Methodology:\n' ...
                '  - ST Charged %% = (ST Charged Energy / Total Charged Energy) × 100\n' ...
                '  - ST Discharged %% = (ST Discharged Energy / Total Discharged Energy) × 100\n' ...
                '  Verification:\n' ...
                '    ST Charged %% = (%.2f / %.2f) × 100 = %.1f%%\n' ...
                '    ST Discharged %% = (%.2f / %.2f) × 100 = %.1f%%\n\n' ...
                'System Performance:\n' ...
                '  Full Cycle Equivalents: %5.1f per studied period\n' ...
                '================================\n'], ...
                results.total_energy.charged, ...
                results.total_energy.discharged, ...
                results.schedule_tx_energy.charged, ...
                results.energy_shares.pct_charged_via_st, ...
                results.schedule_tx_energy.discharged, ...
                results.energy_shares.pct_discharged_via_st, ...
                results.schedule_tx_energy.charged, ...
                results.total_energy.charged, ...
                results.energy_shares.pct_charged_via_st, ...
                results.schedule_tx_energy.discharged, ...
                results.total_energy.discharged, ...
                results.energy_shares.pct_discharged_via_st, ...
                results.FCE);
            
            % Display the formatted results
            disp(output);
        end
    end
end